CREATE TABLE CHUNGNAM_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGNAM_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE BUSAN_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE CHUNGBUK_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);


CREATE TABLE DAEGU_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEGU_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE DAEJEON_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGJU_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GANGWON_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGBUK_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGGI_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE GUNGNAM_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE INCHEON_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEJU_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONBUK_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE JEONNAM_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE SEOUL_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_HOTEL_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_AMUSE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_CONDO_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_CAMPING_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_ELSESLEEP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_DUTYFREE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_LEISURESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_HUGESHOP_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_GOLF_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_SKI_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_CULTURE_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);

CREATE TABLE ULSAN_FOOD_24 (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    predict_month VARCHAR(200),
    predict_value DECIMAL(65,2)
);



