version: '3'
services:
  app:
    image: your-spring-boot-image:latest # 여기에 실제 Spring Boot 애플리케이션 이미지 이름을 넣어주세요
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://database-2.cp0mag4s6790.us-east-2.rds.amazonaws.com:3306/predict_money?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789 # 여기에 실제 MySQL root 비밀번호를 넣어주세요
      MYSQL_DATABASE: predict_money
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789 # 여기에 실제 MySQL 사용자 비밀번호를 넣어주세요
    ports:
      - "3306:3306"
spring:
  datasource: #항상 여기 주석 처리 해야 함
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
  thymeleaf:
    prefix: classpath:/templates/


